language: cpp

compiler:
  - clang++-3.8
  - g++-5

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.8
      - g++-5
      - gcc-5

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_CXX_COMPILER="${CXX}"
  - make -j ${JOBS}
  - ctest
