language: cpp

compiler:
  - clang++
  - g++

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.8
      - g++-5
      - gcc-5

script:
  - [ "${CXX}" = "clang++" ] && CXX="clang++-3.8"
  - [ "${CXX}" = "g++"     ] && CXX="g++-5"
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_CXX_COMPILER="${CXX}"
  - make -j ${JOBS}
  - ctest
